@startuml

package factories {

interface ApplicationFactory {
ApplicationLogger getApplicationLogger()
}

class ApplicationFactoryImpl {
+ApplicationLogger getApplicationLogger()
}

ApplicationFactory <|-- ApplicationFactoryImpl

ApplicationFactory ...> ApplicationLoggerFactory: calls

}

@enduml