@startuml

package factories {

interface ApplicationFactory {
ApplicationLogger getApplicationLogger()
FileValidator getFileValidator()
}

class ApplicationFactoryImpl {
+ApplicationLogger getApplicationLogger()
+FileValidator getFileValidator()
}

ApplicationFactory <|-- ApplicationFactoryImpl

ApplicationFactory ...> ApplicationLoggerFactory: calls

}

@enduml