@startuml


package hansen {

interface HansenPass {
void compile (String inputFile, String, outputFile);
int getErrorCount();
}

}

package passone {

interface PassOne {
}


class PassOneImpl{
+void compile(String inputFile, String outputFile};
}

PassOneImpl --|> PassOne: implements
PassOne...|> HansenPass: extends

}


@enduml