@startuml


package hansen {

interface HansenPass {
}

}

package passtwo {

interface PassTwo {
}


class PassTwoImpl{

}

PassTwoImpl --|> PassTwo: implements
PassTwo...|> HansenPass: extends

}


@enduml